SUSE/ceph

- src/ceph-disk
- src/test/python/ceph_disk/test_ceph_disk_blikid.py
Fixes for the bug
https://bugzilla.suse.com/show_bug.cgi?id=943250
Has some unit tests.
> Fixes to bnc 943250

- systemd/ceph
rgw also started and stopped enabled etc using one command.
Signed-off-by: Owen Synge <osynge@suse.com>
> Extend rcceph to mange rgw

- CMakeLists.txt
> cmake: fix declaration position of WITH_TESTS option

- etc/ceph_ver_hack.sh
> ceph_ver_hack.sh script for OBS/IBS builds (bsc#1015419)

- ceph.spec.in
My idea to conditionalize Source0 was rejected by upstream and, not only that, it causes Tumbleweed submissions to get auto-declined. Clearly it's not worth the trouble.
> Revert conditionalization of Source0: line

- src/ceph-disk/ceph_disk/main.py
- systemd/ceph-disk@.service
- systemd/ceph-osd@.service
> fix systemd ceph-osd boot race condition

- qa/workunits/fs/test_python.sh
- qa/workunits/rados/test_python.sh
- qa/workunits/rbd/notify_master.sh
- qa/workunits/rbd/notify_slave.sh
- qa/workunits/rbd/rbd_mirror.sh
- qa/workunits/rbd/rbd_mirror_stress.sh
- qa/workunits/rbd/test_librbd_python.sh
- qa/workunits/rbd/test_lock_fence.sh
Signed-off-by: Sage Weil <sage@redhat.com>
(cherry picked from commit cf294777ea92f0911813a7132068584d4f73a65a)
conflicts in all modified files, resolved by '-X theirs'
> qa/workunits: use relative path instead of wget from git

- doc/man/8/ceph-deploy.rst
Signed-off-by: Alfredo Deza <adeza@redhat.com>
(cherry picked from commit 9d42a0f88d5d59c5da4977c9ef3474c52801807f)
> doc: ceph-deploy man: remove references to mds destroy. Not implemented

- ceph.spec.in
> build/ops: rpm: adapt License line to Release 2.0 of SPDX spec

- src/osd/PrimaryLogPG.cc
With the transition to the cmpext upstream API, we need to continue to
handle iSCSI gw clients that use the old API. Do so via translation.
This logic should be removed once clients using the old API are no
longer supported, as was done with 8047d61183 ("ReplicatedPG: drop
CACHE_PIN->WRITESAME req translation"). (bsc#1035937).
> ReplicatedPG: add CHECKSUM->CMPEXT req translation

- ceph.spec.in
- install-deps.sh
Fixes: http://tracker.ceph.com/issues/20425
(cherry picked from commit a9fa154a95fb858f5182198e111cc828a29bf7eb)
> build/ops: rpm: put mgr python build dependencies in make_check bcond

- qa/deepsea/tasks.yaml
- qa/suites/deepsea-test.yaml
- qa/tasks/deepsea.py
> tests: deepsea: change default to SUSE/DeepSea.git

- src/common/options.cc
- src/osd/PGLog.cc
- src/osd/PGLog.h
- src/osd/osd_types.h
- src/test/osd/TestPGLog.cc
- src/tools/ceph_objectstore_tool.cc
> luminous: core: osd/PGLog: write only changed dup entries

- src/rgw/rgw_basic_types.h
- src/rgw/rgw_iam_policy.cc
- src/rgw/rgw_iam_policy.h
> luminous: rgw: Remove assertions in IAM Policy

- src/rgw/rgw_rados.h
- src/rgw/rgw_reshard.cc
Fixes:http://tracker.ceph.com/issues/21725
Signed-off-by: Orit Wasserman <owasserm@redhat.com>
(cherry picked from commit f1ec7a49bde054a19a0a8fd80f37866e1e40379f)
> rgw: disable dynamic resharding in multisite environment

- src/rgw/rgw_data_sync.cc
- src/rgw/rgw_data_sync.h
- src/rgw/rgw_dencoder.cc
- src/rgw/rgw_meta_sync_status.h
- src/test/encoding/types.h
bsc#1066182 & http://tracker.ceph.com/issues/22083
> data sync fixes

- src/pybind/mgr/prometheus/module.py
Upon consultation with @jan--f this should take care of the first regression and the second one is not urgent and can wait until 12.2.3.
> prometheus module 500 if 'deep' in pg states

- qa/deepsea/opensuse_15.yaml
- qa/suites/deepsea/adhoc/fs/distros/opensuse_15.yaml
- qa/suites/deepsea/adhoc/health-ok-encrypted/distros/opensuse_15.yaml
- qa/suites/deepsea/adhoc/health-ok/distros/opensuse_15.yaml
- qa/suites/deepsea/adhoc/igw/distros/opensuse_15.yaml
- qa/suites/deepsea/adhoc/nfs-ganesha-both/distros/opensuse_15.yaml
- qa/suites/deepsea/adhoc/nfs-ganesha-cephfs/distros/opensuse_15.yaml
- qa/suites/deepsea/adhoc/nfs-ganesha-rgw/distros/opensuse_15.yaml
- qa/suites/deepsea/adhoc/openattic/distros/opensuse_15.yaml
- qa/suites/deepsea/adhoc/rgw-ssl/distros/opensuse_15.yaml
- qa/suites/deepsea/adhoc/rgw/distros/opensuse_15.yaml
- qa/suites/deepsea/basic/fs/distros/opensuse_15.yaml
- qa/suites/deepsea/basic/health-ok-encrypted/distros/opensuse_15.yaml
- qa/suites/deepsea/basic/health-ok/distros/opensuse_15.yaml
- qa/suites/deepsea/basic/igw/distros/opensuse_15.yaml
- qa/suites/deepsea/basic/nfs-ganesha/distros/opensuse_15.yaml
- qa/suites/deepsea/basic/openattic/distros/opensuse_15.yaml
- qa/suites/deepsea/basic/rgw/distros/opensuse_15.yaml
- qa/suites/suse/smoke/health-ok/distros/opensuse_15.yaml
- qa/suites/suse/smoke/nfs-ganesha/distros/opensuse_15.yaml
- qa/suites/suse/smoke/openattic/distros/opensuse_15.yaml
- qa/suites/suse/smoke/rbd/distros/opensuse_15.yaml
> qa: add openSUSE Leap 15.0 to deepsea and suse/smoke suites

- qa/suites/deepsea/adhoc/fs/exec/health-mds-cli.yaml
- qa/suites/deepsea/adhoc/fs/exec/health-mds.yaml
- qa/suites/deepsea/adhoc/health-ok-dashboard/exec/health-ok-dashboard.yaml
- qa/suites/deepsea/adhoc/health-ok-encrypted/exec/health-ok-encrypted.yaml
- qa/suites/deepsea/adhoc/health-ok/exec/health-ok.yaml
- qa/suites/deepsea/adhoc/nfs-ganesha-both/exec/both-cli.yaml
- qa/suites/deepsea/adhoc/nfs-ganesha-both/exec/both.yaml
- qa/suites/deepsea/adhoc/nfs-ganesha-cephfs/exec/cephfs-cli.yaml
- qa/suites/deepsea/adhoc/nfs-ganesha-cephfs/exec/cephfs.yaml
- qa/suites/deepsea/adhoc/nfs-ganesha-rgw/exec/rgw-cli.yaml
- qa/suites/deepsea/adhoc/nfs-ganesha-rgw/exec/rgw.yaml
- qa/suites/deepsea/adhoc/rgw-ssl/exec/health-rgw-ssl.yaml
- qa/suites/deepsea/adhoc/rgw/exec/health-rgw-cli.yaml
- qa/suites/deepsea/adhoc/rgw/exec/health-rgw.yaml
Posting this as a PR so I don't forget to merge it!
> qa: deepsea/adhoc: do not destroy test cluster if test script fails

- qa/tasks/deepsea.py
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>
>  Add 'install' option to deepsea task 

- qa/deepsea/health-ok/common/deploy.sh
- qa/suites/deepsea/test/cluster/1node.yaml
- qa/suites/deepsea/test/cluster/test_roles.yaml
- qa/suites/deepsea/test/tasks1-deepsea.yaml
- qa/tasks/deepsea.py
- qa/tasks/deepsea_deploy.py
- qa/tasks/salt_manager.py
> qa/deepsea: implement role introspection and split off deepsea_deploy task from deepsea task

- qa/tasks/deepsea.py
Instructions for use:
1. create a yaml file that looks like this:
```
overrides:
deepsea:
log_anchor: MyFineString
```
2. pass that yaml file as positional parameter to `teuthology-openstack` command
3. observe that `MyFineString` appears instead of `WWWW` in the teuthology log.
It should also be possible to set `log_anchor` to `null` or `''`.
---
> qa/tasks/deepsea: introduce configurable log anchor string

- qa/tasks/deepsea.py
Reviewers: just the very last commit :-) Disregard the rest - they will disappear once #229 #230 #231 #232 are merged and this PR is rebased.
> qa/tasks/deepsea: implement MGR dashboard module smoke test

- qa/tasks/salt_manager.py
In the CI we saw:
```
Running: "sudo sh -c 'salt \\* test.ping' 2>/dev/null || true"
The salt master could not be contacted. Is master running?
tasks.salt_manager:0 of 1 minions responded
Running: "sudo sh -c 'salt \\* test.ping' 2>/dev/null || true"
The salt master could not be contacted. Is master running?
tasks.salt_manager:0 of 1 minions responded
ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
File "/home/ubuntu/teuthology/teuthology/run_tasks.py", line 95, in run_tasks
run_one_task(taskname, stack, timer, ctx=ctx, config=config)
File "/home/ubuntu/teuthology/teuthology/run_tasks.py", line 74, in run_one_task
manager.__enter__()
File "/home/ubuntu/teuthology/teuthology/task/__init__.py", line 121, in __enter__
self.begin()
File …
```
> qa/tasks/salt: print debug info when ping fails due to no master

- src/rgw/librgw.cc
bsc#1110415
(will require nfs-ganesha update with librgw)
--
Fixes: http://tracker.ceph.com/issues/36302
Signed-off-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit 1d44ba04513e06978fa1e3115ebb86292d625df4)
> librgw: initialize curl and http client for multisite

- src/rgw/rgw_sync_module_es.cc
rework of https://github.com/SUSE/ceph/pull/213 dropping the already merged fix in 12.2.9 and adding the same PR that is staged at upstream luminous
downstream version of https://github.com/ceph/ceph/pull/25444
bsc#1110415
bsc#1110416
> Ses5 es fixes 2

- src/cls/lock/cls_lock.cc
- src/cls/lock/cls_lock_client.cc
- src/cls/lock/cls_lock_client.h
- src/cls/lock/cls_lock_ops.cc
- src/cls/lock/cls_lock_ops.h
- src/cls/lock/cls_lock_types.h
- src/cls/rgw/cls_rgw.cc
- src/cls/rgw/cls_rgw_client.cc
- src/cls/rgw/cls_rgw_client.h
- src/cls/rgw/cls_rgw_types.h
- src/rgw/rgw_admin.cc
- src/rgw/rgw_bucket.cc
- src/rgw/rgw_bucket.h
- src/rgw/rgw_cr_rados.cc
- src/rgw/rgw_metadata.cc
- src/rgw/rgw_metadata.h
- src/rgw/rgw_rados.cc
- src/rgw/rgw_rados.h
- src/rgw/rgw_reshard.cc
- src/rgw/rgw_reshard.h
- src/test/cli/radosgw-admin/help.t
- src/test/cls_lock/test_cls_lock.cc
- src/test/cls_rgw/test_cls_rgw.cc
- src/test/librados/lock.cc
- src/test/librados_test_stub/LibradosTestStub.cc
Fixes for the following tracker issues:
http://tracker.ceph.com/issues/36688
http://tracker.ceph.com/issues/37446
https://tracker.ceph.com/issues/37555
bsc# 1109009
> Ses5 dynamic reshard fixes

- qa/suites/deepsea/tier3/rbd/3-test-phase.yaml
- qa/workunits/rbd/map-unmap.sh
Successful run http://10.86.2.104:8081/ubuntu-2019-02-02_07:58:34-deepsea:tier3-wip-qa-rbd-journal_ses5---basic-openstack/
> qa:deepsea/tier3: use rbd/journal.sh and map-unmap.sh (backport SES5)

- qa/suites/deepsea/tier1/health-ok/cluster/roles.yaml
- qa/suites/deepsea/tier1/health-ok/deepsea_cli
- qa/suites/deepsea/tier1/health-ok/deepsea_cli_off.yaml
- qa/tasks/deepsea.py
> qa/tier1/health-ok: add prometheus and grafana roles

- qa/tasks/deepsea.py
deployment of the dashboard is now handled by DeepSea itself
in Stage 3
> qa/deepsea: drop dashboard deployment code

- qa/tasks/scripts/ganesha_smoke_test.sh
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>
> qa/tasks: support '-' in array_to_json

- qa/tasks/scripts/iscsi_smoke_test.sh
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>
> qa/tasks: provide iscsiadm correct ip

- qa/tasks/scripts/iscsi_smoke_test.sh
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>
> qa/tasks: iscsiadm should listen on non lo ip address

- src/rgw/rgw_admin.cc
- src/rgw/rgw_bucket.cc
- src/rgw/rgw_bucket.h
- src/rgw/rgw_common.h
- src/rgw/rgw_object_expirer_core.cc
- src/test/cli/radosgw-admin/help.t
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1133139
> Ses5 rgw obj exp fixes

- doc/radosgw/frontends.rst
- src/rgw/rgw_asio_frontend.cc
> Ses6 beast ipv6

- src/rgw/rgw_rest_conn.h
- src/rgw/rgw_sync_module_aws.cc
http://tracker.ceph.com/issues/39364 & http://tracker.ceph.com/issues/39361
Fixes issues found in https://jira.suse.com/browse/SES-97
> Ses6 cloud sync fixes

- src/client/Client.cc
- src/client/Client.h
- src/client/Inode.h
- src/mds/CInode.cc
- src/messages/MClientReply.h
- src/test/libcephfs/test.cc
References: https://jira.suse.com/browse/SES-183
> MDS + libcephfs snapshot btime support

- src/client/Client.cc
Fixes: http://bugzilla.suse.com/show_bug.cgi?id=1135219
Fixes: http://bugzilla.suse.com/show_bug.cgi?id=1135221
> client: fix vxattr nanosecond field padding

- qa/suites/deepsea/functional/2-services-and-test.yaml
- qa/tasks/deepsea.py
> qa/deepsea: add grafana_service_check validation test

- ceph.spec.in
- src/ceph-volume/CMakeLists.txt
- src/ceph-volume/plugin/lvmcache/CMakeLists.txt
- src/ceph-volume/plugin/lvmcache/setup.py
Signed-off-by: Mohamad Gebai <mgebai@suse.com>
> ceph-volume: install lvmcache plugin

- src/ceph-volume/plugin/lvmcache/ceph_volume_lvmcache/main.py
Signed-off-by: Mohamad Gebai <mgebai@suse.com>
> lvmcache: refactor argument parsing and add -h flag

- qa/tasks/scripts/mgr_plugin_dashboard_smoke.sh
Added the check on the Dashboard screen after login and pools screen plus check if the branded files exist on the mgr node.
> Extended branding smoketest

- qa/suites/deepsea/tier1/mgr-modules/2-test-phase.yaml
- qa/tasks/scripts/mgr_plugin_dashboard_smoke.sh
- qa/tasks/ses_qa.py
If this PR happens to have hundreds of commits in it, let me know and I'll rebase it.
> qa/deepsea: expand testing of dashboard SUSE branding

- qa/suites/deepsea/tier3/rbd/0-salt.yaml
- qa/suites/deepsea/tier3/rbd/3-test-phase/cram.yaml
- qa/tasks/cram.py
- src/test/cli-integration/rbd/diff.t
> qa/deepsea: add cram test to tier3/rbd

- qa/tasks/salt.py
References: http://bugzilla.suse.com/show_bug.cgi?id=1132324
> qa/salt: gather rbd-target-api logs

- qa/tasks/ses_qa.py
[skip ci]
Also choose a random drive to replace and properly try to gather the
path
> qa/deepsea: drive replacement fixes

- qa/suites/deepsea/tier4/upgrade/2-pools-and-services.yaml
- qa/suites/deepsea/tier4/upgrade/3-test-phase.yaml
- qa/suites/deepsea/tier4/upgrade/cluster/roles.yaml
- qa/tasks/deepsea.py
- qa/tasks/scripts/iscsi_smoke_test.sh
qa/deepsea: Added ISCSi on ses 5 to 6 upgrade
qa/deepsea: Added optional upgrade argument on iscsi_smoke_test
qa/tasks/deepsea.py: Added 'post_upgrade_policy' and 'remove_openattic'
functions.
qa/deepsea: Added 'cephfs_sanity_test' and 'ganesha_sanity_test'
Signed-off-by: gkyratsas <gkyratsas@suse.com>
> Work In Progress - Will be split

- qa/tasks/scripts/iscsi_smoke_test.sh
This PR adds a fix to make iscsi smoke test to work with deployments of ceph-iscsi with and without SSL enabled.
This PR is required by the DeepSea PR https://github.com/SUSE/DeepSea/pull/1754 to be successfully tested.
> qa/tasks/scripts/iscsi: use HTTPS to connect to ceph-iscsi if api_secure=true

- qa/tasks/scripts.py
> qa/tasks/scripts.py: return stdout of script

- qa/tasks/deepsea.py
This is a fix to ECP CI failures.
Added a sleep in order to prevent the test from failing due to not
rebalancing soon enough, plus a test to check if the osds after the
rebuild are equal to the ones before. 
> qa/tasks/deepsea.py: rebuild_node fix

- qa/tasks/deepsea.py
- qa/tasks/salt.py
- qa/tasks/salt_manager.py
- qa/tasks/ses_qa.py
> qa/tasks: py3 compatibility

- qa/tasks/deepsea.py
The Validation class in deepsea.py has a feature where certain tests are
configured to run every time the class/subtask is invoked. When the
class/subtask is invoked more than once, this is not a good thing because
the default validation tests get run on every invocation.
This patch fixes the issue by ensuring that the default tests are run only
once.
> qa/deepsea: run the default validation tests only once

- qa/tasks/deepsea.py
- qa/tasks/util/__init__.py
Also, if RECENT_CRASH health warning is present, run "ceph crash ls-new".
References: https://jira.suse.com/browse/SES-1312
> qa/deepsea.py: show health details on HEALTH_{ERR,WARN}

- qa/deepsea/health-ok/common/nfs-ganesha.sh
2.8.3 don't ship `/etc/sysconfig/nfs-ganesha` anymore, instead there is `/etc/sysconfig/ganesha`
> Upstream ganesha has different config file name

- qa/tasks/ceph_salt.py
- qa/tasks/salt.py
- qa/tasks/salt_manager.py
- qa/tasks/scripts.py
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>
> qa/tasks/salt: fix module path for py3

- qa/tasks/ceph_salt.py
Add registries and containers via yaml files in order to be able to have
different ones for each case via teuthology overrides
Requires https://gitlab.suse.de/ceph/storage-ci/-/merge_requests/147 to be merged
> qa/tasks/ceph_salt: Add Containers as parameters

- .github/pull_request_template.md
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>
> github: suse specific customization for pull requests

- src/pybind/mgr/cephadm/module.py
Fixes: https://jira.suse.com/browse/SES-1671
Signed-off-by: Patrick Seidensal <pseidensal@suse.com>
---
<details>
</details>
> Monitoring: Use downstream container images

- ceph.spec.in
- src/ceph-volume/CMakeLists.txt
- src/ceph-volume/plugin/__init__.py
- src/ceph-volume/plugin/lvmcache/CMakeLists.txt
- src/ceph-volume/plugin/lvmcache/__init__.py
- src/ceph-volume/plugin/lvmcache/ceph_volume_lvmcache/__init__.py
- src/ceph-volume/plugin/lvmcache/ceph_volume_lvmcache/main.py
- src/ceph-volume/plugin/lvmcache/setup.py
- src/ceph-volume/plugin/lvmcache/tests/test_lvmcache.py
plus three follow up commits
---
<details>
</details>
> [SES7] ceph-volume: add lvmcache plugin

- src/cephadm/cephadm
Prevent any accidential downloads from docker.io
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
---
<details>
</details>
> cephadm: set default image to registry.suse.com/ses/7/ceph/ceph

- qa/suites/deepsea/tier2/drive-replacement/1-deepsea.yaml
- qa/tasks/deepsea.py
- qa/tasks/scripts/drive_replace.sh
- qa/tasks/ses_qa.py
- qa/tasks/util/__init__.py
Also make flake8 happy
---
<details>
</details>
> SES6: qa: suse/tier2/drive-replacement: use dynamic value for drive group limit

- src/cephadm/cephadm
- src/pybind/mgr/cephadm/module.py
Because CaaSP v5 has been renamed to CaaSP v4.5 and v5 has been
scheduled for deletion.
Signed-off-by: Patrick Seidensal <pseidensal@suse.com>
---
<details>
</details>
> Switch to CaaSP v4.5 container images

- src/ceph-volume/ceph_volume/devices/lvm/batch.py
- src/ceph-volume/ceph_volume/tests/devices/lvm/test_batch.py
This pulls in two fixes from the batch refactor PR and fixes bsc#1176960
---
<details>
</details>
> ceph-volume batch: update cherry-picks from batch refactor

- src/rgw/rgw_rest.cc
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1180509
> rgw: Replace COMPLETE_MULTIPART_MAX_LEN with configurable rgw_max_put_param_size

- qa/tasks/scripts/ganesha_smoke_test.sh
- qa/tasks/scripts/mgr_plugin_dashboard_smoke.sh
- src/script/dashboard_e2e_tests.sh
---
Fixes part of the fallout from https://bugzilla.suse.com/show_bug.cgi?id=1183600
> qa/deepsea: set dashboard admin password via -i

- src/cephadm/cephadm
- src/pybind/mgr/cephadm/module.py
Signed-off-by: Patrick Seidensal <pseidensal@suse.com>
Docs update: https://github.com/SUSE/doc-ses/pull/920
---
<details>
</details>
> cephadm: Update Grafana container image from 7.0.3 to 7.3.1

- qa/suites/deepsea/tier2/filestore-to-bluestore-migration/2-test-phase.yaml
- qa/tasks/scripts.py
- qa/tasks/ses_qa.py
> qa: add timeouts to some validation tests

- qa/tasks/ceph_salt.py
- qa/tasks/salt_manager.py
> Gather logfile cephadm.out

- src/cephadm/cephadm
- src/pybind/mgr/cephadm/module.py
Prometheus server: ses/7/prometheus/prometheus-server:2.27.1
Node exporter: ses/7/prometheus/prometheus-node-exporter:1.1.2
Alertmanager: ses/7/prometheus/prometheus-alertmanager:0.21.0
Signed-off-by: Tatjana Dehler <tdehler@suse.com>
---
<details>
</details>
> cephadm: update default monitoring container images

- src/cephadm/cephadm
- src/pybind/mgr/cephadm/module.py
downstream images for test
---
<details>
</details>
> cephadm: use images from registry.suse.de

- src/pybind/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.brand.html
- Fix layout bug of the 'Dashboard' navigation menu.
- Sync branded page with upstream changes, e.g. rename menu item.
- MOTD was not shown.
Before:
After:
Signed-off-by: Volker Theile <vtheile@suse.com>
---
<details>
</details>
> mgr/dashboard: Adapt downstream branded navigation page

- src/cephadm/cephadm
- src/pybind/mgr/cephadm/module.py
2.27.1 -> 2.32.1
---
<details>
</details>
> cephadm: update prometheus-server version

- ceph.spec.in
backport https://github.com/ceph/ceph/pull/45347
Fixes: https://tracker.ceph.com/issues/54530
(cherry picked from commit 781be8d44a8543aca87bba4f61ba47acc6046b49)
---
<details>
</details>
> ses7p: cephadm: preserve `authorized_keys` file during upgrade

- ceph.spec.in
backport https://github.com/ceph/ceph/pull/45347
Fixes: https://tracker.ceph.com/issues/54530
(cherry picked from commit 781be8d44a8543aca87bba4f61ba47acc6046b49)
---
<details>
</details>
> ses7: cephadm: preserve `authorized_keys` file during upgrade

- src/common/dout.h
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1194875
> common: fix FTBFS due to dout & need_dynamic on GCC-12

- src/pybind/mgr/cephadm/services/cephadmservice.py
- src/pybind/mgr/cephadm/services/monitoring.py
backport: https://github.com/ceph/ceph/pull/45333
Fixes: https://tracker.ceph.com/issues/54502
Signed-off-by: Tatjana Dehler <tdehler@suse.com>
(cherry picked from commit https://github.com/SUSE/ceph/commit/a1ee73f3ad600870dba05beab85f2cd21ff8c991)
(cherry picked from commit https://github.com/SUSE/ceph/commit/e233ed01c0d43f6d6debfcd41fb6c4cdd3105e34)
---
<details>
</details>
> ses7: mgr/cephadm: try to get FQDN for configuration files

- src/cephadm/cephadm
- src/cephadm/tests/test_cephadm.py
backport of https://github.com/ceph/ceph/pull/45420
Fixes: https://tracker.ceph.com/issues/54588
(cherry picked from commit 736af2b9c29e375a184b863220641b7d254e7d04)
---
<details>
</details>
> cephadm: infer the default container image during pull

- src/cephadm/cephadm
- src/pybind/mgr/cephadm/module.py
downstream image build of `prometheus-snmp_notifier` for test
---
<details>
</details>
> cephadm: use `snmp-notifier` image from registry.suse.de

- src/cephadm/cephadm
- src/cephadm/tox.ini
- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/tox.ini
after #468
update image paths `registry.suse.de` -> `registry.suse.com`
---
<details>
</details>
> cephadm: update image paths to registry.suse.com

- qa/workunits/cephadm/test_cephadm.sh
- src/cephadm/cephadm
Backport of #45765
---
<details>
</details>
> cephadm: avoid crashing on expected non-zero exit

- src/pybind/mgr/cephadm/inventory.py
- src/pybind/mgr/cephadm/module.py
- src/pybind/mgr/cephadm/services/osd.py
- src/pybind/mgr/cephadm/tests/test_cephadm.py
- src/pybind/mgr/cephadm/tests/test_osd_removal.py
- src/python-common/ceph/deployment/inventory.py
backport of https://github.com/ceph/ceph/pull/39238 and https://github.com/ceph/ceph/pull/39536
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1200317
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).
<details>
- …
> octopus: mgr/cephadm: fix and improve osd draining

- src/pybind/mgr/dashboard/controllers/iscsi.py
- src/pybind/mgr/dashboard/services/iscsi_client.py
Signed-off-by: Mykola Golub <mgolub@suse.com>
(cherry picked from commit 958bc398dcba1cc65770cf01fa75772718c1966a)
<details>
- `jenkins test make …
> mgr/dashboard: allow to pass controls on iscsi disk create

- src/pybind/mgr/cephadm/upgrade.py
backport of https://github.com/ceph/ceph/pull/49921
<details>
- `jenkins test …
> mgr/cephadm: fix handling of mgr upgrades with 3 or more mgrs

- src/pybind/mgr/cephadm/serve.py
- src/pybind/mgr/cephadm/tests/test_cephadm.py
backport of https://github.com/ceph/ceph/pull/49920 and https://github.com/ceph/ceph/pull/51346
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1209621
<details>
- …
> mgr/cephadm: write client files after applying services

- ceph.spec.in
- cmake/modules/CheckCxxAtomic.cmake
> Fix FTBFS on s390x (bsc#1211090)
