SUSE/ceph

- ceph.spec.in
The 50-rbd.rules udev rule is required for the creation of
/dev/rbd/<pool>/<image> symlinks. This change ensures that it is
packaged on openSUSE and SLES platforms.
> ceph.spec.in: package the rbd udev rule on SUSE

- src/ceph-disk
28fb607 was reverted by b6eaf97 but not completely - this vestige was left behind.
> src/ceph-disk: finish reverting 28fb607

- ceph.spec.in
This commit fixes bnc#934343 by making sure 50-rbd.rules is installed in the
right directory and belongs to the ceph-common package.
It also introduces use of %{_udevrulesdir} and makes sure the Red Hat, Fedora,
etc. conditionals do not thwart our fix.
> ceph.spec.in: install 50-rbd.rules in the right place

- ceph.spec.in
- src/rgw/Makefile.am
If ever destined for upstream use, we'd have to add the appropriate Requires/BuildRequires to the rh/fedora conditional under the radosgw section of the spec file.
> fix civetweb https support - bsc#942874

- src/rgw/rgw_rest.cc
Fixes: #12537
Don't send the bucket name back without url encoding it.
Signed-off-by: Yehuda Sadeh <yehuda@redhat.com>
> rgw: url encode exposed bucket

- ceph.spec.in
The %set_permissions macro expands into a "/usr/bin/chkstat --system"
call, which requires the radosgw binary path as a parameter to take
effect.
> ceph.spec.in: use full radosgw path for set_permissions

- src/include/rados.h
- src/osd/ReplicatedPG.cc
- src/osd/ReplicatedPG.h
This goes with kernel patches:
libceph: add support for write same requests
rbd: add support for writesame requests
This adds a new ceph request writesame. Write a buffer of length
writesame.data_length bytes at writesame.offset over writesame.length
bytes.
On the kernel rbd client side, we map this command to the SCSI
WRITE_SAME request.
Signed-off-by: Mike Christie <michaelc@cs.wisc.edu>
Acked-by: David Disseldorp <ddiss@suse.de>
> osd: add write same op (bnc#948925)

- src/osd/ReplicatedPG.cc
COMPARE AND WRITE operations are implemented by the kernel RBD client
using compound cmpext + write OSD requests. Such requests are handled
by OSDs in a serialized fashion, ensuring that no extra locking is
required for object atomicity; (bnc#948986).
> osd: remove unnecessary CMPEXT locking comment

- src/ceph-disk
For a plain dmcrypt device, "create" is the same as open --type plain / plainOpen
bnc: #957385
> get rid of redundandacy in ceph_disk

- ceph.spec.in
The "^system-ceph\\x2" regex catches "system-ceph\x2ddisk\x2dactivate"
"system-ceph\x2ddisk\x2dactivate\x2djournal", "system-ceph\x2dosd", etc.
systemd slices spawned by udev.
> ceph.spec.in: disable udev systemd slices on uninstall

- src/osd/ReplicatedPG.cc
If we proxy the read, we cannot return false, even if we fail to also
trigger a promotion; (bnc#971768).
Fixes: http://tracker.ceph.com/issues/15171
Signed-off-by: Sage Weil <sage@redhat.com>
(cherry picked from commit 7eae05e14231cb3476d14bf74b15bf9646849d09)
> osd/ReplicatedPG: do not proxy read *and* process op locally

- doc/release-notes.rst
- src/common/config_opts.h
- src/test/pybind/test_rbd.py
This reverts commit d24883e4973ae13c50137cf35bdba12bf67d7860.
Use defaults that are compatible with the current Linux kernel RBD
client.
Acked-by: David Disseldorp <ddiss@suse.de>
> Revert "rbd: update default image features"

- src/global/Makefile.am
Rely on dynamic initialization instead. Linking lttng in this way had
the unfortunate side effect of causing radosgw to segfault (when
daemonized) during sigterm processing (ie. during lttng_ust_exit()).
This was originally removed in 638738f, but accidentally re-added via
5f61d36.
Signed-off-by: Karol Mroz <kmroz@suse.com>
(cherry picked from commit 85a727f0a8bb43a41fcabb02613086a7edf84b1b)
Upstream PR: https://github.com/ceph/ceph/pull/8876
> global: don't link lttng into libglobal

- src/rgw/rgw_rados.cc
Fixes: http://tracker.ceph.com/issues/15937
Signed-off-by: Orit Wasserman <owasserm@redhat.com>
(cherry picked from commit b79856bd3f7db8498231d7f35b53b4bcb44a0422)
> rgw: add missing metadata_heap pool to old zones

- src/rgw/rgw_rados.cc
currently for any admin operations like user create etc. you would
always see:
`RGWZoneParams::create(): error creating default zone params: (17) File
Exists`
in stdout as the debug level is set to 0, which doesn't make much sense
for an end user, so skip the error message, callers of the function handle
the error message anyway, so we skip it here
Fixes: http://tracker.ceph.com/issues/15720
(cherry picked from commit 2ace9d7f349ef09d3ed87fb216cda3e305ef706f)
> rgw: remove -EEXIST error msg for ZoneCreate

- systemd/ceph-mds@.service
- systemd/ceph-mon@.service
- systemd/ceph-osd@.service
- systemd/ceph-radosgw@.service
- systemd/ceph-rbd-mirror@.service
This fixes https://bugzilla.suse.com/show_bug.cgi?id=982324 by reverting the commits that add the unsupported lvalues to the systemd unit files.
> Fix for bsc#982324

- ceph.spec.in
> rpm: Fix creation of mount.ceph symbolic link for SUSE distros

- Makefile.am
- ceph.spec.in
- configure.ac
- doc/Makefile.am
- man/Makefile-server.am
- src/Makefile-env.am
- src/Makefile-server.am
- src/Makefile.am
- src/tools/Makefile-server.am
With the changes in this PR, the build of the ceph-test package is disabled by default when building the RPMs for the SUSE distros.
> rpm: build of ceph-test package disabled by default

- ceph.spec.in
Dominique Leuenberger / DimStar wrote:
The only idea I would have in plus for now (which is a really crude
hack) would be as last commands in %install:
rm -rf . (which basically removes all the sources and certainly gains
some space)
This would work, as the files have all been copied to %{buildroot} by
that time and - debuginfo is not split at this moment, which is what
occupies some more space later on - and the fact that 'build' will
attempt to install the built binaries.
> ceph.spec.in: nuke sources at end of %install phase

- ceph.spec.in
This run-time dependency on the ceph package is most likely bogus.
> ceph.spec.in: ceph-devel-compat drop ceph dependency

- ceph.spec.in
We need to get the `Source99: ceph-rpmlintrc` line out of ceph.spec.in because the teuthology buildpackages task chokes on it (the ceph-rpmlintrc file is only in OBS/IBS, not in git):
```
error: Bad file: /tmp/release/SUSE_LINUX/WORKDIR/SOURCES/ceph-rpmlintrc: No such file or directory
```
Replace this line with a comment. The file is needed in OBS/IBS, and the Factory/SLE spec file validation scripts will whine without the spec-file line, but they don't care *which* spec file it is in :-) So we accompany this with a small patch to pre_checkin.sh to add the line to ceph-test.spec.
> ceph.spec.in: drop ceph-rpmlintrc source line

- src/ceph-disk
The code never needs to know the block device size only the free partion space.
We use parted as the output is consitent across these distributions:
SUSE Linux Enterprise Server 12 SP1
openSUSE Leap 42.1 (x86_64)
Debian GNU/Linux 8.3 (jessie)
Fedora release 23 (Twenty Three)
Scientific Linux release 7.2 (Nitrogen)
Scientific Linux release 6.7 (Carbon)
Backported from bd3832b5de4f3f03aa2449af930d4ad965f8c22b
Signed-off-by: Owen Synge <osynge@suse.com>
> ceph_disk.main: s/get_dev_size/get_free_partition_size/

- m4/ax_arm.m4
- src/common/Makefile.am
- src/common/crc32c_aarch64.c
The used compiler may or may not be recent enough to recognize the
crc32 extended cpu type. However, it does not really have to know about
them either, since all we do is pass inline assembly instructions to
the assembler.
This patch moves the crc cpu extension detection from compiler based
to assembler based, so that we can build optimized code even when the
compiler does not know about the cpu type yet.
Signed-off-by: Alexander Graf <agraf@suse.de>
> AArch64: Detect crc32 extension support from assembler

- src/rgw/rgw_op.cc
Fixes: http://tracker.ceph.com/issues/17698
Signed-off-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit e9cf41f9bfd1aa7d35f945f6a3ee6bb66c135bad)
(Cherry-picked from upstream master PR https://github.com/ceph/ceph/pull/11648 which hasn't been merged yet.)
> rgw: fix for bucket delete racing with mdlog sync

- src/test/cli/rbd/help.t
https://bugzilla.suse.com/show_bug.cgi?id=978423
https://build.suse.de/package/show/Devel:Storage:4.0:Staging:Testing/ceph
In SES3/4 we are carrying downstream commit
8aee8db140bcbd1ffd2a7b571dbbade10bec9de3 which causes "make check" to fail at
src/test/cli/rbd/help.t with output like:
```
--image-feature arg       image features
-                            [layering(+), striping, exclusive-lock(+*),
-                            object-map(+*), fast-diff(+*), deep-flatten(+-),
+                            [layering(+), striping(+), exclusive-lock(*),
+                            object-map(*), fast-diff(*), deep-flatten(-),
journaling(*)]
```
This commit adapts the test to match the actual rbd help output.
Signed-off-by: smithfarm <ncutler@suse.com>
> tests: adapt rbd CLI help test for SES3/4

- ceph.spec.in
I don't know for sure, but it seems reasonable to assume that the tests in
"make check" expect the binaries from ceph-test to be built.
> ceph.spec.in: make check only in ceph-test package

- ceph.spec.in
Here we are trying to be helpful on upgrade by ensuring that log files are
owned by the ceph user, but it turns out we were being too cautious. The
/var/log/ceph directory might not be owned by ceph and the log files might have
names like foo.log-20151215
References: https://bugzilla.suse.com/show_bug.cgi?id=1010930#c13
> rpm: expand log file ownership change

- qa/workunits/fs/test_python.sh
- qa/workunits/rados/test_python.sh
- qa/workunits/rbd/notify_master.sh
- qa/workunits/rbd/notify_slave.sh
- qa/workunits/rbd/rbd_mirror.sh
- qa/workunits/rbd/rbd_mirror_stress.sh
- qa/workunits/rbd/test_librbd_python.sh
- qa/workunits/rbd/test_lock_fence.sh
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1000105
In the past, upstream was wgetting lots of stuff directly from github for their automated integration testing. This turned out to be not so good, because github would often time out or be unavailable.
To fix this, upstream started maintaining a mirror of the main github repo at git.ceph.com.
While this mirror is accessible from OVH, it does not have the downstream SHA1s that we are testing, so the wget fails.
To fix this, revert to downloading directly from github (hoping that it will work) and use SUSE/ceph.git instead of ceph/ceph.git.
> tests: wget test python scripts from github.com/SUSE/ceph

- qa/workunits/fs/test_python.sh
- qa/workunits/rados/test_python.sh
- qa/workunits/rbd/notify_master.sh
- qa/workunits/rbd/notify_slave.sh
- qa/workunits/rbd/rbd_mirror.sh
- qa/workunits/rbd/rbd_mirror_stress.sh
- qa/workunits/rbd/test_librbd_python.sh
- qa/workunits/rbd/test_lock_fence.sh
... because downstream SHA1s are available only from github.
In the past, upstream was wgetting lots of stuff directly from github for their
automated integration testing. This turned out to be not so good, because
github would often time out or be unavailable.
To fix this, upstream started maintaining a mirror of the main github repo at
git.ceph.com.
While this mirror is accessible from anywhere, it does not have the downstream
SHA1s that we are testing, so the wget fails.
To fix this, revert to downloading directly from github (hoping that it will
work) and use SUSE/ceph.git instead of ceph/ceph.git.
Also, raw.github.com forwards to raw.githubusercontent, so avoid one redirect.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1000105 …
> tests: wget test code directly from github

- ceph.spec.in
This reverts commits 30000255973986169ca9162f9e92cb5a78fa7015 and
eb81424461ee4cdfad11bde44eab92e36f2ca62e and brings this section
of the spec file into line with upstream.
> Revert "rpm: fix ownership of logfiles in %pre"

- ceph.spec.in
Analogous change to d8f5376fef0cc0e0fb492651e85650a240e5b63f
> rpm: expand log file reown for ceph-radosgw

- ceph.spec.in
For FATE#321098 etc. we need to ship the ceph client code for these architectures. That means we have to somehow build the entire ceph.spec
> Tweak ceph.spec for ppc64le and s390(x) client build

- ceph.spec.in
https://github.com/openSUSE/spec-cleaner/commit/e8c4df75d65931df11e9b3cf9b67ed756306364b
added the ability to disable the openSUSE spec-cleaner.
Since our downstream spec file is heavily based on the upstream version and we
want to minimize divergence, it makes sense to never let spec-cleaner have its
way with the file.
> rpm: tell openSUSE to never clean the spec file

- ceph.spec.in
- debian/control
The bc is missing for ceph-helpers.sh
> Add bc dependency to ceph spec

- ceph.spec.in
. . . and put all Group: lines in SUSE conditional blocks.
Fixes: http://tracker.ceph.com/issues/19184
(cherry picked from commit a3d6d4f75ed10ec62c2b56bdfa5290e8131d3198)
Conflicts:
ceph.spec.in (no %{epoch} in downstream spec file)
> build/ops: make package groups comply with openSUSE guidelines

- qa/workunits/suites/iozone.sh
ceph-cm-ansible does not install workunit dependencies on openSUSE or SLES.
This commit works around that by making the iozone workunit install the iozone
package from OBS on these OSes before trying to run the iozone executable.
> tests: workunit: install iozone package from OBS (openSUSE/SLES only)

- src/rgw/rgw_civetweb_frontend.cc
Since the array we used needs additional check to ensure that the size
is correct, and causes undefined behaviour in a few platforms, using a
vector and passing the c array back to mg_start so that we don't go past
the end of array.
Signed-off-by: Jesse Williamson <jwilliamson@suse.de>
(cherry picked from commit 426564dcaec242aaa0436af93183deaa92984245)
> rgw: use a vector for options passed to civetweb

- src/crypto/isa-l/CMakeLists.txt
Companion commit to 693b882e3f2d2bc0bcfd16302a9f9a9d0836c3f9
To fix build error:
```
[ 2474s] CMake Error at src/crypto/isa-l/cmake_install.cmake:68 (file):
[ 2474s]   file RPATH_CHANGE could not write new RPATH:
[ 2474s] 
[ 2474s]     /usr/lib64/ceph
[ 2474s] 
[ 2474s]   to the file:
[ 2474s] 
[ 2474s]     /home/abuild/rpmbuild/BUILDROOT/ceph-12.0.2+git.1493227670.3396ca1-1.1.x86_64/usr/lib64/ceph/crypto/libceph_crypto_isal.so.1.0.0
[ 2474s] 
[ 2474s]   No valid ELF RPATH or RUNPATH entry exists in the file;
[ 2474s] Call Stack (most recent call first):
[ 2474s]   src/cmake_install.cmake:384 (include)
[ 2474s]   cmake_install.cmake:37 (include)
[ 2474s]   
[ 2474s] 
[ 2474s] 
[ 2474s] Makefile:83: recipe for target 'install' failed
[ 2474s] make: *** [install] Error 1
```
> cmake: added empty RPATH to libceph_crypto_isal.so

- src/include/rados.h
- src/include/rados/librados.h
- src/include/rados/librados.hpp
- src/librados/IoCtxImpl.cc
- src/librados/IoCtxImpl.h
- src/librados/librados.cc
- src/osd/PrimaryLogPG.cc
- src/osd/PrimaryLogPG.h
- src/osdc/Objecter.h
- src/test/librados/aio.cc
- src/test/librados/c_read_operations.cc
- src/test/librados/c_write_operations.cc
- src/test/librados/misc.cc
- src/tracing/librados.tp
- src/tracing/osd.tp
This patchset is a straight cherry-pick of the upstream OSD/librados cmpext changes.
(bsc#1035937).
> cmpext backport from upstream master

- ceph.spec.in
Avoids FTBFS in openSUSE Tumbleweed with GCC7:
[ 1225s] Scanning dependencies of target cython3_cephfs
[ 1225s] Traceback (most recent call last):
[ 1225s]   File "/home/abuild/rpmbuild/BUILD/ceph-12.0.2+git.1493295295.8c88dc6/src/pybind/cephfs/setup.py", line 18, in <module>
[ 1225s]     from setuptools import setup
[ 1225s]   File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
[ 1225s]     from six.moves import filter, map
[ 1225s] ModuleNotFoundError: No module named 'six'
[ 1225s] make[2]: *** [src/pybind/cephfs3/CMakeFiles/cython3_cephfs.dir/build.make:57: src/pybind/cephfs3/CMakeFiles/cython3_cephfs] Error 1
[ 1225s] make[1]: *** [CMakeFiles/Makefile2:3653: src/pybind/cephfs3/CMakeFiles/cython3_cephfs.dir/all] Error 2
[ 1225s] make[1]: *** Waiting …
> build/ops: rpm: install python-six in build environment

- src/osd/PrimaryLogPG.cc
With SES2[.1], writesame used rados write opcode 36. With SES3 and later
write opcode 36 has been assigned to cache-pin. writesame instead uses
write opcode 38, which was accepted upstream. To handle the SES2[.1] ->
SES3 API mismatch, CACHE_PIN -> WRITESAME request transformation logic
was added (via 99468458f269029ca6c6cbe158059fa669d5dcaf).
With SES2.1 iSCSI gateways no longer supported, this logic can be
removed from the SES5 branch, reducing the upstream delta.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1038063
Reviewed-by: Jan Fajerski <jfajerski@suse.com>
> ReplicatedPG: drop CACHE_PIN->WRITESAME req translation

- ceph.spec.in
I can no longer reproduce the build failure that this was "fixing".
> Revert "build/ops: rpm: install python-six in build environment"

- qa/deepsea/2disks.yaml
- qa/deepsea/2nodes.yaml
- qa/deepsea/3nodes.yaml
- qa/deepsea/4nodes.yaml
- qa/deepsea/health-mds.yaml
- qa/deepsea/health-ok.yaml
- qa/suites/deepsea-test.yaml
- qa/suites/deepsea/basic/2nodes/health-mds/2disks.yaml
- qa/suites/deepsea/basic/2nodes/health-mds/2nodes.yaml
- qa/suites/deepsea/basic/2nodes/health-mds/health-mds.yaml
- qa/suites/deepsea/basic/2nodes/health-ok/2disks.yaml
- qa/suites/deepsea/basic/2nodes/health-ok/2nodes.yaml
- qa/suites/deepsea/basic/2nodes/health-ok/health-ok.yaml
- qa/suites/deepsea/basic/3nodes/health-mds/2disks.yaml
- qa/suites/deepsea/basic/3nodes/health-mds/3nodes.yaml
- qa/suites/deepsea/basic/3nodes/health-mds/health-mds.yaml
- qa/suites/deepsea/basic/3nodes/health-ok/2disks.yaml
- qa/suites/deepsea/basic/3nodes/health-ok/3nodes.yaml
- qa/suites/deepsea/basic/3nodes/health-ok/health-ok.yaml
- qa/suites/deepsea/basic/4nodes/health-ok/2disks.yaml
- qa/suites/deepsea/basic/4nodes/health-ok/4nodes.yaml
- qa/suites/deepsea/basic/4nodes/health-ok/health-ok.yaml
- qa/tasks/deepsea.py
Also breaks up the test yaml into reusable chunks (stored in `qa/deepsea/`) and implements a "DeepSea integration test suite" under `qa/suites/deepsea/` to enable teuthology to automate the tests.
N.B.: This is the companion PR to https://github.com/SUSE/DeepSea/pull/322
> qa: changes to deepsea task to enable CephFS integration testing

- etc/ceph_ver_hack.sh
With this patch, the code for setting "ceph --version" will ignore tags that
don't start with a lower-case "v", opening up the door for us to add downstream
tags to our product branches.
> ceph_ver_hack.sh: use git describe --match

- qa/suites/deepsea/ceph-test/rbd-cli-generic/tasks/1-rbd-cli-generic.yaml
This is a stopgap measure - I still haven't figured out why this test script [*] isn't failing upstream.
[*] https://github.com/ceph/ceph/blob/master/qa/workunits/rbd/cli_generic.sh
> qa: create rbd pool before running rbd test

- src/osd/PrimaryLogPG.cc
- src/osd/PrimaryLogPG.h
6f860ff8da36bd74954b5982ce4cc1741b34bcfe added functionality to munge
old (SES <= 4) cmpext requests and responses, to ensure that clients
weren't affected by the API change.
cmpext on EC support (04cf38cc159479417562da36848537ee99892d7d), added
a cmpext asynchronous completion handler which broke response munging.
This change reinstates cmpext response munging, ensuring that the munged
request state is tracked through to the completion handler.
(bsc#1047244).
> osd: move CMPEXT response munging into completion function

- ceph.spec.in
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1047020
and paves the way to dropping libxio
> ceph.spec.in: obsolete libxio

- src/ceph_release
Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit 8f0945a0f39e7da629fa94f406bc1314e1b39fc8)
> ceph_release: luminous is now 'stable' (12.2.x)

- ceph.spec.in
Fixes: http://tracker.ceph.com/issues/21176
> build/ops: python-numpy-devel build dependency for SUSE

- qa/suites/deepsea/basic/openattic/cluster/2nodes2disks.yaml
- qa/suites/deepsea/basic/openattic/cluster/3nodes2disks.yaml
Companion PR to https://github.com/SUSE/DeepSea/pull/643 (merge it first, then this one)
> tests: deepsea: use 3-node cluster for openATTIC deployment

- src/ceph-disk/ceph_disk/main.py
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1051598
Signed-off-by: Chao Xiong <cxiong@suse.com>
Acked-by: Nathan Cutler <ncutler@suse.com>
> ceph-disk: fix mountpoint check for systemctl enable --runtime

- src/rgw/rgw_auth_s3.h
- src/rgw/rgw_swift_auth.h
Fixes: http://tracker.ceph.com/issues/21400
Upstream master PR: https://github.com/ceph/ceph/pull/17775
currently we create a keystone revocation thread even when keystone url
is empty, lets defer the construction of keystone unless the urls are
configured
(cherry picked from commit 104c2f59011e6b515e3845cce529ee44334e76c0)
> rgw: defer constructing keystone engine unless url is configured

- systemd/ceph-mds@.service
- systemd/ceph-mon@.service
- systemd/ceph-osd@.service
- systemd/ceph-radosgw@.service
- systemd/ceph-rbd-mirror@.service
To prevent bugs like https://bugzilla.suse.com/show_bug.cgi?id=1061461
IIRC the original revert was done because the systemd in SLES did not understand the TasksMax parameter. But I tried it with the systemd that is in SLE-12-SP3 and it worked fine.
> systemd: restore TasksMax=infinity

- src/rgw/rgw_keystone.h
Thread::join triggers an assert otherwise.
Fixes http://tracker.ceph.com/issues/21666
Signed-off-by: Karol Mroz <kmroz@suse.de>
(cherry picked from commit 26f2da083c7dd21b89c1c1e6c498b14e034364a6)
> rgw: stop/join TokenCache revoke thread only if started.

- src/rgw/rgw_data_sync.cc
http://tracker.ceph.com/issues/21938 & 
bsc#1066182
> luminous: multisite: data sync status advances despite failure in RGWListBucketIndexesCR

- src/common/ceph_json.h
- src/rgw/rgw_json_enc.cc
In order to support jewel-luminous multisite scenarios where when a
jewel cluster is the master, the sync-from-all json field wouldn't be
set leading to the secondary not syncing data as this value can't be
overriden to true, so defaulting the value of sync_from_all to true when
we don't encounter it in the json
Fixes: http://tracker.ceph.com/issues/22062 (tagged for backports as well)
bsc#1067705
(cherry picked from commit e0116fa42020ff5c0d78101b9b3b15e62236b4b8)
> rgw: set sync_from_all as true when no value is seen

- src/rgw/rgw_auth_keystone.cc
When keystone engine is used and there is an error (often due to
misconfigured urls etc) these do not show up at the final logs as we
just return  -1 at the final stage. Adding logs at level 5 for these
cases, as they can help identify a possible misconfigured url or admin
token. Eg:
```
5 Failed keystone auth from http://localhost:5000/v3/v3/auth/tokens with 404
```
Fixes: http://tracker.ceph.com/issues/22151
bsc#1060904
(cherry picked from commit 347c5148a57de9007d6c1293add6bf27004fce41)
> rgw: keystone: bump up logging when error is received

- src/ceph-disk/tox.ini
Very old, and very new, versions of flake8 treat E722 as an error:
```
flake8 runtests: commands[0] | flake8 --ignore=H105,H405,E127 ceph_disk tests
ceph_disk/main.py:1575:9: E722 do not use bare except'
ceph_disk/main.py:1582:9: E722 do not use bare except'
ceph_disk/main.py:3252:5: E722 do not use bare except'
ceph_disk/main.py:3288:21: E722 do not use bare except'
ceph_disk/main.py:3296:17: E722 do not use bare except'
ceph_disk/main.py:4358:5: E722 do not use bare except'
tests/test_main.py:26:1: E722 do not use bare except'
ERROR: InvocationError: '/opt/j/ws/mkck/src/ceph-disk/.tox/flake8/bin/flake8 --ignore=H105,H405,E127 ceph_disk tests'
```
References: https://gitlab.com/pycqa/flake8/issues/361
> tests: ceph-disk: ignore E722 in flake8 test

- src/crush/CrushCompiler.cc
- src/test/cli/osdmaptool/create-racks.t
bsc#1067119 has this as a PTF, so it needs to go into the 12.2.2 maintenance update
> tools/crushtool: skip device id if no name exists

- src/rgw/rgw_op.cc
> rgw: multipart uploads are broken if the bucket has been resharded

- qa/deepsea/tasks.yaml
- qa/suites/deepsea/ceph-test/pynfs/fsal/cephfs.yaml
- qa/tasks/deepsea.py
The deepsea spec file was templated recently. This was causing teuthology jobs
to fail when DeepSea was installed from source.
> tests: deepsea: obtain dependencies from deepsea.spec.in

- src/rgw/rgw_asio_client.cc
- src/rgw/rgw_asio_client.h
- src/rgw/rgw_civetweb.cc
- src/rgw/rgw_civetweb.h
- src/rgw/rgw_client_io.cc
- src/rgw/rgw_client_io.h
- src/rgw/rgw_fcgi.cc
- src/rgw/rgw_fcgi.h
- src/rgw/rgw_lib.h
- src/rgw/rgw_loadgen.cc
- src/rgw/rgw_loadgen.h
- src/rgw/rgw_process.cc
Since web frontends may signal an error when requests are malformed or so, let
us double check this and raise errors early. The current user of this is
civetweb frontend; which can potentially return null from `parse_http_headers`
when a HTTP header without a ":" is supplied at which point headers.value is
null which can lead to undefined behaviour later in RGW.
Fixes: http://tracker.ceph.com/issues/23039
(cherry picked from commit 7872a831783e17dcc4d0aa70cffc256afb664f7a)
Conflicts:
-	src/rgw/rgw_asio_client.h
keeping get_conn_close which is a part of L
-	src/rgw/rgw_lib.h
dropping init.env changes introduced in mimic
> rgw:  make init env methods return an error

- src/pybind/mgr/dashboard/CMakeLists.txt
The dashboard will run on Python 3 downstream, so test it on that version.
> qa: test dashboard with Python 3

- src/ceph-detect-init/CMakeLists.txt
- src/ceph-detect-init/Makefile.am
- src/ceph-detect-init/tox.ini
- src/ceph-disk/CMakeLists.txt
- src/ceph-disk/Makefile.am
- src/ceph-disk/tox.ini
- src/tools/setup-virtualenv.sh
--use-wheel was deprecated in favor of --only-binary in pip v7.0.0. and
--use-wheel was removed in a recent release of pip. but some packages
are source packages, so we cannot simply replace use-wheel with
only-binary. so a simpler approach is to drop --use-wheel option, as pip
respects --find-links, and will find the required package from the
wheelhouse.
Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit a80cce4ba6afee921a7c6adce802c91e30f8c0a9)
Conflicts:
src/ceph-detect-init/CMakeLists.txt
src/ceph-disk/CMakeLists.txt: trivial resolution
src/pybind/mgr/dashboard/CMakeLists.txt: dashboard2 is not
in luminous, so drop this change.
src/tools/setup-virtualenv.sh:
src/ceph-detect-init/Makefile.am:
src/ceph-disk/Makefile.am: these files were dropped in
master, so update …
> src: s/--use-wheel//

- etc/ceph_ver_hack.sh
In luminous, cmake takes care of populating src/ceph_ver.h.in.cmake. For our tar_scm OBS source service-based tarball generation, the only file we need to populate is src/.git_version.
See the cmake code at https://github.com/SUSE/ceph/blob/ses5/src/CMakeLists.txt#L212-L219
> ceph-ver-hack.sh: do not touch src/ceph_ver.h.in.cmake

- src/ceph-disk/ceph_disk/main.py
Python2 to Python3 changed the return of map() from a list to a
"map object" which is an interator. This commit turns the returned
"map object" back into a list.
Signed-off-by: Alexander Graul <agraul@suse.com>
Fixes https://github.com/SUSE/DeepSea/issues/1247
> let extract_parted_partition_numbers return a list

- src/mgr/MgrClient.cc
Without holding the lock update_daemon_health() can race with
send_report() corrupting the daemon_health_metrics vector.
Fixes: http://tracker.ceph.com/issues/23352
Signed-off-by: Kjetil Joergensen <kjetil@medallia.com>
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>
(cherry picked from commit 4996506a6b4ab309110039ea29a075f14d09a379)
Conflicts:
src/mgr/MgrClient.cc Function name is different in luminous
> luminous: mgr/MgrClient: Protect daemon_health_metrics

- src/rgw/rgw_auth_s3.cc
While s3 docs mention that every byte must be urlencoded, they are relaxed in
its implementation, when testing this behaviour on aws s3 itself, they seem to
be relaxed in handling aws credentials of the form
X-Amz-Credential=access1/20180817T123456Z/us-east-1...
wherein
X-Amz-Credential=access1%2F2018...
is expected. This allows for clients requesting the urls in both forms to
succeed as aws s3 does at the moment
bsc#1105251
Fixes: http://tracker.ceph.com/issues/26965 (needs backport)
> rgw: s3: awsv4 drop special handling for x-amz-credential

- src/ceph-disk/ceph_disk/main.py
In python 3, dev is a string, but mounts_dev is bytes, so they can't
compare equal, resulting in is_mounted() returning None for mounted
OSDs.
> ceph-disk: compatibility fix for python 3

- qa/deepsea/deepsea.yaml
- qa/tasks/deepsea.py
- qa/tasks/salt.py
- qa/tasks/salt_manager.py
- qa/workunits/deepsea/common/deploy.sh
- qa/workunits/deepsea/common/helper.sh
and add salt_manager.py helper module used by both the Salt and DeepSea tasks. This will be joined by a teuthology companion PR.
To Do:
> qa: split off Salt task from DeepSea task

- src/cls/rgw/cls_rgw.cc
- src/cls/rgw/cls_rgw_types.cc
- src/rgw/rgw_reshard.cc
Currently we don't copy the actual_stats field during reshard, which makes
resharded buckets show a size_utilized as 0, which further has the problem that
a subsequent object removal would subtract the object size from the 0 size
utilized showing up large uint64_t values. Copy the size_actual from the source
object in both cls and in reshard_process. This will fix the new buckets,
existing buckets will still have to go through a bucket check --fix for their
stats to be corrected.
bsc#1110419 
Fixes: http://tracker.ceph.com/issues/36290
(cherry picked from commit beb90638ae3d5329653b61bae0d6714796c41d04)
> rgw: copy actual stats from the source shards during reshard

- qa/deepsea/health-ok/common/deploy.sh
- qa/suites/deepsea/test/tasks1-deepsea.yaml
- qa/tasks/deepsea.py
- qa/tasks/deepsea_deploy.py
- qa/tasks/salt.py
- qa/tasks/salt_manager.py
Feature-parity with health-ok.sh achieved.
See qa/suites/deepsea/test/tasks1-deepsea.yaml for how to use.
---
> qa/tasks/deepsea_deploy.py: implement built-in Stage 0 capability 

- qa/deepsea/health-ok/common/deploy.sh
- qa/deepsea/health-ok/health-ok.sh
- qa/suites/deepsea/test/cluster/0disks.yaml
- qa/suites/deepsea/test/cluster/3disks.yaml
- qa/suites/deepsea/test/cluster/test_roles.yaml
- qa/suites/deepsea/test/tasks1-deepsea.yaml
- qa/tasks/deepsea_deploy.py
- qa/tasks/salt.py
- qa/tasks/util/__init__.py
Implementation of Stage 1 is complete. Stage 2 is still missing a lot - notably, non-default storage profiles. Also, currently the "default profile" deploys OSDs on all eligible disks on every storage node. This is non-intuitive, because the roles stanza (in the teutholoy job yaml) expects to specify the number of osd roles (OSDs) on the individual test nodes.
---
> qa/deepsea_deploy: implement Stage 1 (fully) and Stage 2 (partially)

- qa/tasks/deepsea.py
Successful run @ http://10.86.2.1/ubuntu-2018-11-13_10:00:02-deepsea:tier0:health-ok-wip-rados-striper---basic-openstack/5/teuthology.log
> qa/tasks/deepsea : add check for rados --striper functionality

- qa/tasks/deepsea.py
Kind of like a mini supportconfig.
(needs testing - DNM yet)
> qa/tasks/deepsea: run "rpm -qa" on test failure

- qa/tasks/deepsea.py
> qa/tasks/deepsea: make rados striper test os_version-aware

- qa/deepsea/stage4.yaml
- qa/suites/deepsea/tier4/upgrade/2-pools-and-services.yaml
- qa/suites/deepsea/tier4/upgrade/3-test-phase.yaml
- qa/suites/deepsea/tier4/upgrade/cluster/roles.yaml
- qa/suites/deepsea/tier4/upgrade/deepsea_cli
- qa/tasks/deepsea.py
- qa/tasks/salt.py
- qa/tasks/scripts.py
- qa/tasks/scripts/clobber_repositories.sh
- qa/tasks/util/__init__.py
> [SES5] qa: introducing the deepsea.repository subtask and automated upgrade testing

- src/rgw/rgw_rados.cc
- src/test/rgw/rgw_multi/multisite.py
- src/test/rgw/rgw_multi/tests.py
This pr attempts to fix a couple of issues around zone deletion. Currently zone deletion and a subsequent period update doesn't validate that the master zone of that zonegroup exists, whereas RGWRados::init_complete will do such a validation making the cluster unuseable. Workaround this in case of an empty zone list, continue initialization. Additionally period update now validates that master zone referenced in a zonegroup is an existant zone (so that in case of a deletion of a multi-zone zonegroup, a master deletion must ensure that a new zone is made the master for period update to succeed). Example reproducer for these scenarios are present in the tracker.
bsc#1116205 & bsc#1112872
Fixes: http://tracker.ceph.com/issues/37328
> Ses5 zone deletion fixes

- qa/tasks/deepsea.py
Occasionally a node does not respond to SSH after reboot.
> qa/deepsea: increase reboot_tries from 15 to 30

- qa/tasks/deepsea.py
In SES6 (and SES5 since 12.2.10), Ceph uses a higher default value of
osd_memory_target (4GiB) which might cause OOM in longer-running tests,
especially when we start using OpenStack flavors with 4GiB of RAM instead of
8GiB.
Note: the OSD might not start if the osd_memory_target is set *too* low.
Use the value recommended in https://tracker.ceph.com/issues/37507#note-4
References: https://trello.com/c/X5StTYxZ/378-teuthology-runs-in-ecp-use-needlessly-large-flavor
Related-to: https://github.com/SUSE/teuthology/pull/176
> qa/tasks/deepsea: set osd_memory_target to 1GiB

- qa/suites/deepsea/tier3/rbd/3-test-phase.yaml
Teuthology run: 
http://10.86.2.104/ubuntu-2019-01-25_13:02:15-deepsea:tier3-wip-qa-rbd-journal---basic-openstack/6/teuthology.log
PS. `rbd bench-write` is replaced by `rbd bench --io-type write` . Upstream PR will follow up...
> Use rbd/journal.sh upstream workunit as replacement for bench-write from qa-automation

- src/rgw/rgw_common.cc
Signed-off-by: Pritha Srivastava <prsrivas@redhat.com>
> rgw: Fix for SignatureMismatchError in s3 commands.

- qa/deepsea/distros/sle_15.0.yaml
- qa/deepsea/distros/sle_15.1.yaml
- qa/distros/all/sle_15.1.yaml
- qa/tasks/scripts/salt_api_test.sh
> qa/deepsea: switch default SLE version from 15.0 to 15.1

- ceph.spec.in
The use of $FIRST_ARG was probably required because of the %service_*
rpm macros were playing tricks one the shell positional
parameters. This is bad practice and error prones so let's assume that
no macros should do that anymore and hence it's safe to assume that
positional parameters remains unchanged after any rpm macro call.
> Drop use of $FIRST_ARG in ceph.spec.in

- qa/tasks/deepsea.py
Lately we have been seeing mysterious 'is running as PID xxxx and was started'
failures, and this is is needed to debug them.
> qa/deepsea: run jobs.active before and after every orchestration

- src/rgw/rgw_common.h
- src/rgw/rgw_file.h
Currently, the authorize function in rgw_file only use the secret key of
first key pair to compare, add a function which get secret key by user's
access key and check the result is match with user's secret key.
Fixes: https://tracker.ceph.com/issues/37855
Signed-off-by: MinSheng Lin <minsheng.l@inwinstack.com>
(cherry picked from commit e92755c60325475342afcafcd5293a20e3e5216a)
> rgw_file: use correct secret key to check auth

- src/crypto/openssl/CMakeLists.txt
See 235448879e5 for explanation.
Fixes: https://bugzilla.opensuse.org/show_bug.cgi?id=1129921
> cmake: empty INSTALL_RPATH for libceph_crypto_openssl.so

- ceph.spec.in
Downstream-only commit. This package is not supported or shipped in SES6.
References: https://jira.suse.de/browse/SES-176
> [DOWNSTREAM] rpm: drop Recommends: ceph-mgr-ssh

- ceph.spec.in
- qa/deepsea/health-ok/common/common.sh
- qa/deepsea/health-ok/common/deploy.sh
- qa/deepsea/health-ok/common/helper.sh
- qa/deepsea/health-ok/health-ok.sh
- qa/deepsea/health-ok/health-openattic.sh
- qa/deepsea/health-ok/stage-5.sh
This commit adds a "ceph-qa-health-ok" subpackage to ceph.spec.in so we can continue running "health-openattic.sh" to deploy a ceph cluster for openATTIC CI testing purposes even now that https://github.com/SUSE/DeepSea/pull/1566 has been merged.
> [SES5] rpm: add downstream-only ceph-qa-health-ok subpackage

- qa/tasks/deepsea.py
- qa/tasks/util/__init__.py
- Verification run http://10.86.3.20/ubuntu-2019-05-06_15:47:05-deepsea:tier1-wip-qa-rpm-ceph-test---basic-openstack/4/teuthology.log
> qa:tasks:deepsea Log warning if ceph and ceph-test RPMs have different versions after stage.2

- src/osd/PrimaryLogPG.cc
- src/osd/PrimaryLogPG.h
This is a forward port of 6f860ff8da36bd74954b5982ce4cc1741b34bcfe and
a8ae498fc193e7fe085a7e54576cee7701ca0863 from the ses5 branch, with both
commits squashed together.
With the transition to the cmpext upstream API, we need to continue to
handle iSCSI gw clients that use the old API. Do so via translation.
This logic should be removed once clients using the old API are no
longer supported, as was done with 8047d61183 ("ReplicatedPG: drop
CACHE_PIN->WRITESAME req translation").
cmpext on EC support (04cf38cc159479417562da36848537ee99892d7d), added
a cmpext asynchronous completion handler which required relocation of
cmpext response munging and extra request state tracking. (bsc#1123360).
(cherry picked from commit …
> ReplicatedPG: add CHECKSUM->CMPEXT req translation

- qa/deepsea/boilerplate/ceph_cm_salt.yaml
> qa/deepsea: use ceph_cm_ansible: false instead of ceph_cm: salt

- qa/tasks/salt.py
- qa/tasks/util/__init__.py
Putting it on stdout makes the teuthology.log file unnecessarily large.
> qa/deepsea: redirect journalctl output to a logfile

- src/common/options.cc
If Ceph is not patched to suppress this warning, customers performing the
upgrade manually will unavoidably get HEALTH_WARN when the Nautilus MON
cluster forms. Then they can either manually issue a command to suppress it
or, alternatively, tolerate HEALTH_WARN status until DeepSea Stage 3 is run
later in the procedure.
This cognitive dissonance can be eliminated by this simple patch. The disadvantage
of diverging from upstream is outweighed by the usability benefit.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1124957
> common: make ms_bind_msgr2 default to "false"

- ceph.spec.in
Follow-up commit to https://github.com/SUSE/ceph/commit/efb8dfad8f0
> rpm: make python3-rgw replace python-rgw on upgrade

- src/pybind/mgr/dashboard/frontend/src/app/ceph/block/iscsi-target-form/iscsi-target-form.component.html
Fixes: http://bugzilla.suse.com/show_bug.cgi?id=1137261
---
This PR will warn that `tcmu-runner` backstore is tech-preview:
Signed-off-by: Ricardo Marques <rimarques@suse.com>
> mgr/dashboard: Warn that tcmu-runner backstore is tech-preview

- qa/tasks/util/__init__.py
[skip ci] Should prevent cases like:
```
sudo journalctl --all > /var/log/journalctl.log
/var/log/journalctl.log: Permission denied
```
> qa:tasks:util: fix log write permission error

- src/rgw/rgw_op.cc
bsc#1137189
Upstream counterpart https://github.com/ceph/ceph/pull/29898 is still open.
To be submitted as a pre-14.2.3 maintenance update.
> rgw: Move upload_info declaration out of conditional

- qa/tasks/util/__init__.py
[skip ci] Should prevent cases like:
```
sudo journalctl --all > /var/log/journalctl.log
/var/log/journalctl.log: Permission denied
```
(cherry picked from commit 86773345c4c1064ad390684c81261116cdb3be36)
> [SES5] [backport] qa:tasks:util: fix log write permission error

- qa/tasks/deepsea.py
Added a check to handle the case that the osds are not passing as an input on assert_bluestore
> qa/tasks/deepsea.py Empty list check @assert_store

- src/ceph-volume/ceph_volume/log.py
- src/ceph-volume/ceph_volume/main.py
- src/ceph-volume/ceph_volume/terminal.py
- src/ceph-volume/ceph_volume/tests/functional/scripts/output.py
- src/ceph-volume/ceph_volume/tests/functional/scripts/test_unicode.sh
- src/ceph-volume/ceph_volume/tests/test_terminal.py
- src/ceph-volume/shell_tox.ini
as requested by @jan--f 
Fixes: https://github.com/SUSE/DeepSea/issues/1747
> ceph-volume: fix stderr failure to decode/encode when redirected

- qa/tasks/deepsea.py
The CLI cannot handle all possible Salt/Jinja syntax, and running anything
other than the DeepSea Stages is out of scope for it.
(cherry picked from commit 99971515fd15710d5a28ff5a92984d918aba79cd)
> [SES5] qa/deepsea: never use DeepSea CLI to run orchestrations

- qa/tasks/deepsea.py
In order to ease the roll-out of ganesha.report to the various CIs.
> qa/deepsea: do not fail the test if ganesha.report not present

- qa/tasks/deepsea.py
- qa/tasks/salt.py
- qa/tasks/salt_manager.py
- qa/tasks/ses_qa.py
(cherry picked from commit 29f036121e24bf5b8043709c0e0d64b2a8e4bbde)
Conflicts:
qa/tasks/salt_manager.py
`gather_logs` was extended meanwhile...
> [SES5] [backport] qa/tasks: py3 compatibility

- src/test/osd/safe-to-destroy.sh
> test/osd/safe-to-destroy.sh: explicitly set v1 protocol in --mon-host setting

- qa/deepsea/health-ok/common/deploy.sh
- qa/deepsea/health-ok/health-ok.sh
We don't use the deploy phase anymore, so nfs_ganesha_debug_log was not
getting triggered.
> qa/health-ok: move ganesha debug log to test phase

- qa/deepsea/health-ok/common/nfs-ganesha.sh
It's not enough to sed both files while ignoring errors. The test tries
to cat the file as well.
> qa/health-ok: check /etc/sysconfig/{ganesha,nfs-ganesha}

- qa/deepsea/health-ok/common/nfs-ganesha.sh
Addresses the error:
+ ETC_SYSCONFIG=/etc/sysconfig/ganesha
+ sed -i s/NIV_EVENT/NIV_FULL_DEBUG/g
sed: no input files
> qa/health-ok: disable param substitution in here doc

- qa/tasks/deepsea.py
(cherry picked from commit 3160c2216f9874a15ff92ab106c9e0cf10938ad8)
> qa: tasks/deepsea: use python2 on SES5

- qa/tasks/deepsea.py
This file is supposed to be maintained in a linter-passing state.
This is defined in the comment at the top of the file:
"""
Task (and subtasks) for automating deployment of Ceph using DeepSea
Linter:
flake8 --max-line-length=100
"""
Somehow it was not passing the linter -- either it started out that way,
or it drifted out of the ideal state over time.
> qa/tasks/deepsea.py: get it passing linter again

- src/common/options.cc
Works around: https://bugzilla.suse.com/show_bug.cgi?id=1171367
> Set OSD's bluefs-buffered-io param to false by default

- install-deps.sh
This ensures that "python3-devel" and "python3-base" will have the exact
same version number, avoiding failures like:
01:22:57   Could NOT find Python3Libs: Found unsuitable version "3.4.10", but required
01:22:57   is exact version "3.4.6" (found /usr/lib64/libpython3.4m.so)
> install-deps.sh: force install python3-devel and python3-base

- qa/tasks/util/__init__.py
Added unhandled exception that's causing tests to fail in case of reboots.
> qa/tasks/util: add exception on remote_exec

- qa/suites/deepsea/tier4/upgrade/1-deploy-phase.yaml
- qa/suites/deepsea/tier4/upgrade/3-test-phase.yaml
Switching to `upgrade.status` instead of `status.report` as it shows more
clear information and it's in accordance with docs and provide 2 minor fixes for the test
- Installing deepsea-cli on the master node in order to fix CI failure due to failure of deepsea commands after upgrade.
- SIlencing health-warning status for `pool(s) have non-power-of-two pg_num` since it's not a requirement on luminous so it's expected behaviour that's currently causing the test to fail
> qa/suites/deepsea/tier4/upgrade: Switching to upgrade.status + 2 fixes

- qa/deepsea/boilerplate/disable-subvolume-check.yaml
- qa/deepsea/health-ok/common/common.sh
- qa/tasks/deepsea.py
Fix introduce support for 2 new deepsea task options:
cluster_network: defines ceph cluster network
public_network: defines ceph public network
In both cases network configuration written to '/srv/pillar/ceph/stack/ceph/cluster.yml'
Signed-off-by: Roman Grigorev <rgrigorev@suse.de>
> Add support for ceph network configuration via deepsea

- qa/tasks/scripts/ses_rack_dc_region_unavailability.sh
Commands tries to run:
`salt target-ses-057.teuthology` while minion is now named
`target-ses-057.ecp.suse.de`
---
<details>
</details>
> qa: ses_rack_dc_region_unavailability: Use wildcard suffix for minion

- qa/tasks/ceph_salt.py
Fixing the path for adding the registry on ceph-salt that was introduced
by MR #262
(https://github.com/ceph/ceph-salt/commit/407853ad5367d79c4378e19e29b31d13f938f306)
---
<details>
- `jenkins test dashboard backend`
</details>
> qa/tasks/ceph_salt.py: Fix ceph-salt registries

- src/pybind/mgr/cephadm/module.py
> [downstream] cephadm: use registry.suse.com by default

- qa/suites/deepsea/build-validation/ses_rgw_zones/cluster/1disk.yaml
- qa/suites/deepsea/build-validation/ses_rgw_zones/cluster/2disks.yaml
- qa/tasks/scripts/ses_disk_fault_injection.sh
- qa/tasks/scripts/ses_removing_osd.sh
- qa/tasks/scripts/ses_replace_disk_part1.sh
- qa/tasks/scripts/ses_replace_disk_part2.sh
- qa/tasks/scripts/ses_stop_osd_daemon.sh
Salt's json output was getting polluted with messages like:
```return event: {'target-ses-023.ecp.suse.de': {'ret': '  WARNING: Failed to connect to lvmetad. Falling back to device scanning.\nvdb', 'retcode': 0, 'jid': '20200704075708748556'}}```
while the expectance was to have 'vdb' only
ses_rgw_zone: add more OSDs to fix TOO_MANY_PGS health warning which was
causing failure
Use "better" regex for fetching OSD ids
---
<details>
</details>
> SES6: qa: Fix ses_disk_fault_injection, ses_rgw_zones, ses_removing_osd tests

- qa/suites/deepsea/functional-1node/boilerplate
- qa/suites/deepsea/functional-3nodes/boilerplate
- qa/tasks/deepsea.py
- Current ceph version for SES6 is 14.2.11+ so this timeout should not be needed.
- Hardware runs for `tier2/functional-{1,3}node/s` lacks the `disable-subvolume-check.yaml` which is provided by the `boilerplate` folder.
---
<details>
</details>
> SES6: qa: Disable 3m sleep after stage.3 and add boilerplate to functional-{1,3}node tests

- qa/tasks/ceph_salt.py
The ceph image path config node was renamed in ceph-salt 15.2.11.
> qa/ceph_salt: Fix ceph image path config

- src/ceph-volume/ceph_volume/devices/lvm/batch.py
(cherry picked from commit 7c0583332d839f7589461d4aba3a45cb43b1f0d4)
Same as #409 but against ses7-m17. Feel free to use whatever is easier and close the other.
---
<details>
</details>
> [SES7] ceph-volume: batch: call the right prepare method

- src/ceph-volume/ceph_volume/devices/lvm/batch.py
(cherry-picked from 7c0583332d839f7589461d4aba3a45cb43b1f0d4)
This is a hotfix commit for rook deployments.
---
<details>
</details>
> ceph-volume: batch: call the right prepare method

- src/pybind/mgr/dashboard/frontend/src/app/shared/services/doc.service.spec.ts
Adds the downstream branding to the ceph dashboard.
- Fixes bz:1177078
-> Former branding pr: https://github.com/SUSE/ceph/pull/392
> mgr/dashboard: Downstream branding

- src/ceph-volume/plugin/lvmcache/ceph_volume_lvmcache/main.py
Fixes: bsc#1175781
This was meant to be fixed on ses7 first, but the plugin was dropped. Still need the fix in ses6.
---
<details>
</details>
> ceph-volume: lvmcache: print help correctly

- qa/tasks/ceph_salt.py
Change timeserver path in ceph-salt as per changes on https://github.com/ceph/ceph-salt/pull/439
---
<details>
</details>
> qa/tasks/cep_salt: Fix timeserver path

- src/pybind/mgr/dashboard/frontend/src/app/shared/services/doc.service.ts
The anchors are changed in the downstream docs.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1178073
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
---
<details>
</details>
> mgr/dashboard: fix downstream NFS doc links

- src/common/options.cc
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1178531
> cephadm: set default container_image to registry.suse.com/ses/7/ceph/ceph

- qa/suites/deepsea/tier2/nfs-ganesha/2-services-and-test/cephfs.yaml
- qa/suites/deepsea/tier2/nfs-ganesha/2-services-and-test/rgw.yaml
After the DeepSea Stages complete, we were running ganesha.report immediately
and seeing the following error:
Exception: Object conf-target-ses-060 does not exist
indicating that the rados object created during Stage 4 is somehow not created
(or not _fully_ created?) and that more time is needed.
Obviously this is not an ideal fix. Ideally, the rados command for creating the
object would not return before the object is fully created.
References: https://bugzilla.suse.com/show_bug.cgi?id=1179621
> qa/deepsea/tier2/nfs-ganesha: insert sleep before ganesha.report

- src/ceph-volume/ceph_volume/drive_group/main.py
Otherwise the drive-group spec potentially tries to pull in the root
device (if it fits).
Fixes: https://tracker.ceph.com/issues/48631
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1180107
Cherry-picks: https://github.com/ceph/ceph/pull/38610
(cherry picked from commit a6a03d0f5535a053239ae9e49c53ac9208bb0738)
---
<details>
</details>
> ceph-volume: pass --filter-for-batch from drive-group subcommand

- qa/tasks/scripts/iscsi_smoke_test.sh
If we have two nodes and they have similar ip addresses,
like 192.168.0.4 and 192.168.0.40 than the mask will match
all of them, that we do not want to.
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>
---
<details>
</details>
> iscsi_smoke_test: fix mask for by-path iscsi host device

- qa/tasks/deepsea.py
As of 14.2.20 we now have to issue the following command after bringing the
cluster up, otherwise the cluster gets stuck in HEALTH_WARN:
ceph config set mon auth_allow_insecure_global_id_reclaim false
> deepsea.yaml: do not fail on 14.2.20 and above

- src/os/filestore/BtrfsFileStoreBackend.cc
- src/os/filestore/FileStore.cc
- src/os/filestore/HashIndex.cc
- src/os/filestore/LFNIndex.cc
Downstream cherry-picks of two upstream nautilus backport PRs, both of which have been merged but not yet released:
* https://github.com/ceph/ceph/pull/40987 (bsc#1183760)
* https://github.com/ceph/ceph/pull/41238 (bsc#1185049)
(Needed to get a maintenance update out by June 18 deadline.)
> ses6-mu19 cherry-picks for deadline

- src/pybind/mgr/zabbix/module.py
Adapt zabbix_sender default path to work for SUSE built container
images, where the `zabbix-agent` package installs `zabbix_sender` to
`usr/sbin/zabbix_sender`.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1186348
Signed-off-by: Patrick Seidensal <pseidensal@suse.com>
---
<details>
</details>
> [SES7] mgr/zabbix: adapt zabbix_sender default path

- src/pybind/mgr/mgr_module.py
- src/pybind/mgr/orchestrator/tests/test_orchestrator.py
Make parsing of keyword arguments a bit safer by
makeing sure the key is actually a valid parameter name
Fixes: https://tracker.ceph.com/issues/47185
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
(cherry picked from commit 922f962ae123b94ee7f92722190d19280f4ef6e3)
---
<details>
</details>
> mgr/mgr_module.py: CLICommand: Fix parsing of kwargs arguments

- src/cephadm/cephadm
- src/pybind/mgr/cephadm/module.py
This commit replaces the following three earlier downstream commits:
273ab431cf78ccdc80a7b7b7b6dad47ef847f935 cephadm: use full qualified image names for cephadm
8e915845164d88e70e56fc472764148e50d53fa3 Switch to CaaSP v4.5 container images
584bc37f75d9b372dc5d7dc2a64618f0a7415a52 cephadm: Update Grafana container image from 7.0.3 to 7.3.1
The reason for replacing them is: in Octopus 15.2.15, upstream introduced the
following global variables for storing the default container image paths:
DEFAULT_PROMETHEUS_IMAGE
DEFAULT_NODE_EXPORTER_IMAGE
DEFAULT_ALERT_MANAGER_IMAGE
DEFAULT_GRAFANA_IMAGE
Now that the default image paths are stored in these global variables, the three
original downstream commits no longer applied cleanly. Furthermore, it's cleaner
to "downstream-ify" these four default …
> cephadm: downstream-ify default container image paths

- src/cephadm/cephadm
- src/pybind/mgr/cephadm/module.py
*  update prometheus-server image version from `2.27.1` to `2.32.1`
*  monitoring stack container images will have moved to the `ceph` path
---
<details>
</details>
> Update Prometheus Container image paths

- doc/mgr/prometheus.rst
- monitoring/grafana/dashboards/host-details.json
- monitoring/grafana/dashboards/hosts-overview.json
- monitoring/grafana/dashboards/osd-device-details.json
- src/pybind/mgr/dashboard/cherrypy_backports.py
- src/pybind/mgr/prometheus/module.py
- src/pybind/mgr/prometheus/test_module.py
- src/pybind/mgr/requirements.txt
- src/pybind/mgr/tox.ini
Still pending upstream backport PR: https://github.com/ceph/ceph/pull/44924
<hr>
Fix issues with PromQL expressions and vector matching with the
`ceph_disk_occupation` metric.
As it turns out, `ceph_disk_occupation` cannot simply be used as
expected, as there seem to be some edge cases for users that have
several OSDs on a single disk.  This leads to issues which cannot be
approached by PromQL alone (many-to-many PromQL erros).  The data we
have expected is simply different in some rare cases.
I have not found a sole PromQL solution to this issue. What we basically
need is the following.
1. Match on labels `host` and `instance` to get one or more OSD names
from a metadata metric (`ceph_disk_occupation`) to let a user know
about which OSDs belong to which disk.
2. Match on labels …
> mgr/prometheus: Fix regression with OSD/host details/overview dashboards

- src/pybind/mgr/cephadm/services/cephadmservice.py
- src/pybind/mgr/cephadm/services/monitoring.py
backport: https://github.com/ceph/ceph/pull/45333
Fixes: https://tracker.ceph.com/issues/54502
Signed-off-by: Tatjana Dehler <tdehler@suse.com>
(cherry picked from commit 30385068eed7a4f93179e8d2748dd6e01bba6ffd)
(cherry picked from commit 4f14993b1667fff309cd9cd6f9dad638a5a7e502)
---
<details>
</details>
> ses7p: mgr/cephadm: try to get FQDN for configuration files

- src/cephadm/cephadm
backport of https://github.com/ceph/ceph/pull/45420
Fixes: https://tracker.ceph.com/issues/54588
(cherry picked from commit 736af2b9c29e375a184b863220641b7d254e7d04)
(cherry picked from commit 2d48d22bfc3e340c504b15a67237acd9b189691e)
---
<details>
</details>
> cephadm: infer the default container image during pull

- src/pybind/mgr/dashboard/module.py
- src/pybind/mgr/dashboard/plugins/ses7p_motd.py
Let the Dashboard module configure the MOTD itself instead doing that via cephadm or ceph-salt. The new approach seems to be the easier way.
To do so, the Dashboard plugin 'ses7p_motd' has been introduced. This should prevent or reduce the number of merge conflicts.
The plugin makes sure it will not configure the MOTD on every start of the Ceph Dashboard module. This way it is possible that the administrator can disable the MOTD manually.
Fixes: https://jira.suse.com/browse/SES-2697
Signed-off-by: Volker Theile <vtheile@suse.com>
---
<details>
- `jenkins test …
> [SES7] Notify user that there is a SES7.1 upgrade available

- src/include/buffer.h
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1194875
> [SES7P] include/buffer: include <memory>

- ceph.spec.in
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1196733
Fixes: https://tracker.ceph.com/issues/55079
(cherry picked from commits aa18cb12003e3526c8e8f23dc2335a483fbfa68e and 94ad178bdcbae56a8eafc65a3a276e25d7a51a5e)
> ceph.spec.in: remove build directory during %clean (bsc#1196733) 

- src/cephadm/cephadm
- src/cephadm/tests/test_cephadm.py
Prometheus is currently using only the hostname in the 'generatorURL' of an alert which causes issues when clicking on the URL in the Ceph Dashboard or somewhere else, because in most cases the hostname of the node that is running the Prometheus container is not resolvable.
To fix that the command line argument '--web.external-url' must be appended in the systemd unit file of the Prometheus container, e.g. '--web.external-url http://foo.bar:9095' whereas a FQDN hostname is used.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1196044
Fixes: https://tracker.ceph.com/issues/55595
Signed-off-by: Volker Theile <vtheile@suse.com>
(cherry picked from commit 4281dc1bbc466dd061781a984b34bb0eafaf482f)
---
<details> …
> cephadm: prometheus: The generatorURL in alerts is only using hostname (bsc#1196044)

- src/cephadm/cephadm
- src/cephadm/tests/test_cephadm.py
- src/cephadm/tox.ini
- src/common/options.cc
- src/pybind/mgr/cephadm/upgrade.py
- src/pybind/mgr/tox.ini
Two things here, the main issue being setting the default container_image to registry.suse.com/ses/7.1/ceph/ceph. The other thing is the `normalize_image_digest()` function, which AFAICT is extremely unlikely to actually cause trouble, but just in case it does, I've made it raise an error rather than silently doing something stupid ;-)
> Remove last vestiges of docker.io image paths

- src/rgw/rgw_cr_rados.cc
- src/rgw/rgw_cr_rados.h
to avoid using not properly initialized bs.bucket_obj.
Fixes: https://tracker.ceph.com/issues/54119
Signed-off-by: Mykola Golub <mgolub@suse.com>
(cherry picked from commit 02c6a56f49571183cd599932b26ff90c2b4b7683)
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1195359
<details>
<summary>Show available Jenkins …
> rgw: check bucket shard init status in RGWRadosBILogTrimCR

- monitoring/prometheus/alerts/ceph_default_alerts.yml
- monitoring/prometheus/alerts/test_alerts.yml
Backport a fix to SES-6 due to a customer having received a PTF. Upstream tracker refuses to add a backport tracker ticket as Nautilus has been closed, saying `An issue assigned to a closed version cannot be reopened`.
---
<details>
</details>
> mgr/dashboard: Incorrect MTU mismatch warning

- ceph.spec.in
This is a temporary downstream fix so that Ceph will continue to build on openSUSE Factory, which is updating to fmt version 9.  Ceph currently fails to build when using fmt 9 (see https://tracker.ceph.com/issues/56610), so this fix will unstick us on Factory until we can get a proper fix upstream. Note that per fmt changelog, the FMT_DEPRECATED_OSTREAM define will be removed in the next major release, but we'll be good with this immediately for the time being.  See:
https://github.com/fmtlib/fmt/blob/master/ChangeLog.rst#900---2022-07-04
Fixes: https://bugzilla.opensuse.org/show_bug.cgi?id=1202292
> ceph.spec.in: Add -DFMT_DEPRECATED_OSTREAM to CXXFLAGS

- .gitignore
- cmake/modules/BuildRocksDB.cmake
- cmake/modules/rocksdb-gcc-13.patch
- src/common/Cycles.h
- src/common/subsys_types.h
- src/librbd/api/PoolMetadata.h
- src/test/mon/test_log_rss_usage.cc
This was reported on the openSUSE side at https://bugzilla.suse.com/show_bug.cgi?id=1201088 and also upstream by one of the Fedora folks at https://tracker.ceph.com/issues/58477.
I've done several builds of this, first to make sure it doesn't break existing (older) GCC in:
- https://build.opensuse.org/package/show/home:tserong:branches:filesystems:ceph/ceph
- https://build.suse.de/package/show/home:tserong:branches:Devel:Storage:7.0:Pacific/ceph
...and of course to make sure it works with GCC 13, but I did that on my local machine with `osc build --alternative-project devel:gcc:next ceph.spec`.
I'm currently working on submitting this upstream too, but the fix to upstream main is slightly different than in pacific and may take a little longer to sort out.
> Fix FTBFS on gcc 13

- src/ceph-volume/ceph_volume/devices/raw/list.py
bea9f4b643c introduced a regression that makes the activate process take a very long time to complete.
`_get_bluestore_info()` which calls `ceph-bluestore-tool` binary via subprocess is called in an exponential way while this is not needed.
Fixes: https://tracker.ceph.com/issues/57627
Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>
(cherry picked from commit 8d7423c3e75afbe111c91e699ef3cb1c0beee61b)
> ceph-volume: fix regression in activate

- src/mgr/ActivePyModules.cc
When dumping the config the cpython may drop/take the gil which may lead to a deadlock when another cpython thread is trying to get the config lock while holding the gil.
Fixes: https://tracker.ceph.com/issues/58269
Signed-off-by: Mykola Golub <mgolub@suse.com>
(cherry picked from commit 133a46e8fd96f24184d129a4b0898c65263221a2)
> mgr: don't dump global config holding gil

- src/pybind/mgr/cephadm/tests/test_scheduling.py
- src/pybind/mgr/cephadm/utils.py
During failover, when haproxy and nfs-ganesha reside on the same host, the backend haproxy config also needs to be reconfigured to reference the newly deployed nfs-ganehsa daemon, but that is only possible if the failed haproxy daemon is also redeployed onto a new host.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1209621
- …
> cephadm: reschedule haproxy from an offline host

- cmake/modules/BuildBoost.cmake
- cmake/modules/boost-python-fix-python-310-pep-620-incompatibility.patch
The included patch comes from https://github.com/boostorg/python/commit/500194edb7833d0627ce7a2595fec49d0aae2484
Note that in BuildBoost.cmake, additional patches just use COMMAND, not PATCH_COMMAND (see "Miscellaneous Options" at https://cmake.org/cmake/help/latest/module/ExternalProject.html)
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1210944
> cmake: patch boost source to support python 3.11

- ceph.spec.in
Signed-off-by: Andreas Schwab <schwab@suse.de>
(cherry picked from commit c7f5037293737322a20617bd7e43ab28da258d22)
> ceph.spec.in: enable build on riscv64 for openSUSE Factory

- ceph.spec.in
This is based on a change made to fix the build on openSUSE Factory which now includes Cython 0.29.x and Cython 3:
https://build.opensuse.org/request/show/1104240
Ceph currently only builds with Cython 0.29, hence the need to exclude version 3 which would otherwise be used by default.
Unfortunately the fix for Factory doesn't work when building against SLE 15 SP3, due to older python macros, hence this version.
> ceph.spec.in: Require Cython >= 0.29 but < 3
